CREATE TABLE BAZUS_SUB_MAP 
   (	"SUBJECT_NAME" VARCHAR2(250), 
	"FORM_NAME" VARCHAR2(250), 
	"SUB_FORM_INTEGRATION_ID" VARCHAR2(20 BYTE), 
	"SUB_INTEGRATION_ID" VARCHAR2(20 BYTE)
   ) TABLESPACE "USERS";
   
create index BAZUS_SUB_MAP1 on BAZUS_SUB_MAP(SUB_FORM_INTEGRATION_ID);
create index BAZUS_SUB_MAP2 on BAZUS_SUB_MAP(SUB_INTEGRATION_ID);

alter table int_plan add alerts varchar2(250);
