 CREATE TABLE INT_CLASSES 
   (ID NUMBER, 
	DAY DATE, 
	HOUR_FROM VARCHAR2(5 BYTE), 
	HOUR_TO VARCHAR2(5 BYTE), 
	NO_FROM NUMBER, 
	NO_TO NUMBER, 
	SUB_ID NUMBER, 
	FOR_ID NUMBER, 
	INTEGRATION_ID_SUB VARCHAR2(30 BYTE), 
	INTEGRATION_ID_FOR VARCHAR2(30 BYTE), 
	PLAN_INTEGRATION_ID VARCHAR2(500 BYTE), 
	TT_COMB_CNT NUMBER, 
	SUM NUMBER, 
	DESC1 VARCHAR2(255 BYTE), 
	DESC2 VARCHAR2(255 BYTE), 
	MERGED_ID VARCHAR2(500 BYTE), 
	CALC_LEC_IDS VARCHAR2(255 BYTE), 
	CALC_GRO_IDS VARCHAR2(255 BYTE), 
	CALC_ROM_IDS VARCHAR2(255 BYTE)
   ) TABLESPACE USERS ;

  CREATE INDEX INT_CLASS_I1 ON INT_CLASSES (CALC_LEC_IDS) 
  TABLESPACE USERS ;

  CREATE INDEX INT_CLASS_I2 ON INT_CLASSES (CALC_GRO_IDS) 
  TABLESPACE USERS ;

  CREATE INDEX INT_CLASS_I3 ON INT_CLASSES (CALC_ROM_IDS) 
  TABLESPACE USERS ;

  CREATE INDEX INT_CLASS_I4 ON INT_CLASSES (SUB_ID) 
  TABLESPACE USERS ;

  CREATE INDEX INT_CLASS_I5 ON INT_CLASSES (FOR_ID) 
  TABLESPACE USERS ;

  CREATE INDEX INT_CLASS_I6 ON INT_CLASSES (DAY) 
  TABLESPACE USERS ;
  
    CREATE TABLE INT_CLASS_MEMBERS 
   (	CLA_ID NUMBER, 
	LEC_GRO_ROM VARCHAR2(3 BYTE), 
	LEC_GRO_ROM_ID NUMBER, 
	INTEGRATION_ID VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  TABLESPACE USERS ;

  CREATE INDEX INT_CLASS_MEMBERS_I1 ON INT_CLASS_MEMBERS (CLA_ID) 
  TABLESPACE USERS ;
  
  