--select * from system_parameters where name like 'VERSION%' order by name desc
INSERT INTO system_parameters (name,value) VALUES ('VERSION 2025.12.20', 'INSTALLED');
commit;

DROP INDEX ROOM_UK;
ALTER TABLE ROOMS MODIFY (NAME VARCHAR2(25 BYTE) );
ALTER TABLE ROOMS_HISTORY MODIFY (NAME VARCHAR2(25 BYTE) );
CREATE UNIQUE INDEX ROOM_UK ON ROOMS (CASE "RESCAT_ID" WHEN 1 THEN "NAME"||' '||"ATTRIBS_01" ELSE TO_CHAR("ID") END ) TABLESPACE "USERS" ;

