create user "PLANNERREPORTS" identified by "123"
grant "CONNECT" to "PLANNERREPORTS";
grant "RESOURCE" to "PLANNERREPORTS";
--select 'grant select on planner.'||lower(table_name)||' to plannerreports;' from cat where table_type = 'TABLE' order by
grant execute on planner.getSQLValues to plannerreports;
grant select on planner.classes to plannerreports;
grant select on planner.flex_col_usage to plannerreports;
grant select on planner.form_formulas to plannerreports;
grant select on planner.forms to plannerreports;
grant select on planner.for_pla to plannerreports;
grant select on planner.gro_cla to plannerreports;
grant select on planner.gro_pla to plannerreports;
grant select on planner.groups to plannerreports;
grant select on planner.lec_cla to plannerreports;
grant select on planner.lec_pla to plannerreports;
grant select on planner.lecturers to plannerreports;
grant select on planner.lookups to plannerreports;
grant select on planner.org_units to plannerreports;
grant select on planner.periods to plannerreports;
grant select on planner.planners to plannerreports;
grant select on planner.reservations to plannerreports;
grant select on planner.res_hints to plannerreports;
grant select on planner.resource_categories to plannerreports;
grant select on planner.str_elems to plannerreports;
grant select on planner.rol_pla to plannerreports;
grant select on planner.rom_cla to plannerreports;
grant select on planner.rom_pla to plannerreports;
grant select on planner.rooms to plannerreports;
grant select on planner.subjects to plannerreports;
grant select on planner.sub_pla to plannerreports;
grant select on planner.system_parameters to plannerreports;
grant select on planner.tmp_numbers to plannerreports;
grant select on planner.tmp_selected_dates to plannerreports;
grant select on planner.tmp_varchar2 to plannerreports;
grant select on planner.value_sets to plannerreports;
