DECLARE CURSOR TEMP
IS
select 'DROP PUBLIC SYNONYM '||SNAME S from SYS.SYNONYMS WHERE CREATOR = USER AND SYNTYPE = 'PUBLIC';
C INTEGER;
BEGIN
FOR REC_TEMP IN TEMP
LOOP
 C := DBMS_SQL.OPEN_CURSOR;
 DBMS_SQL.PARSE(C, REC_TEMP.S,DBMS_SQL.V7);
 DBMS_SQL.CLOSE_CURSOR(C);
 END LOOP;
END;
/

DECLARE
CURSOR TEMP
IS
select 'CREATE PUBLIC SYNONYM '||object_name||' FOR '||object_name S from sys.all_objects where owner = user and
OBJECT_TYPE NOT IN ('SYNONYM', 'INDEX', 'PACKAGE BODY') order by object_name;
C INTEGER;
BEGIN
FOR REC_TEMP IN TEMP
LOOP
 C := DBMS_SQL.OPEN_CURSOR;
 BEGIN
 DBMS_SQL.PARSE(C, REC_TEMP.S,DBMS_SQL.V7);
 EXCEPTION -- ZABLOKOWANIE ZATRZYMANIA Z POWODU BŁĘDÓW
 WHEN OTHERS THEN
 NULL; -- POLECENIE RAISE PODNOSI WYJĄTEK
 END;
 DBMS_SQL.CLOSE_CURSOR(C);
 END LOOP;
END;
/

begin
delete from SYSTEM_PARAMETERS where name = 'PLANOWANIE.LICENCE_FOR';
insert into SYSTEM_PARAMETERS (name, value) values ('PLANOWANIE.LICENCE_FOR', 'DEMO');
commit;
end;
/