
DROP TABLE DETAILS;
DROP TABLE DETAIL_CONTEXTS;

CREATE TABLE DETAIL_CONTEXTS ( ID NUMBER PRIMARY KEY, NAME VARCHAR2(100), TYPE VARCHAR2(100));


CREATE TABLE DETAILS
( ID                NUMBER primary key,
  PARENT_ID         NUMBER,
  CONTEXT_ID        NUMBER,
  COLOUR            INTEGER,
  DESC1             VARCHAR2(200 BYTE),
  DESC2             VARCHAR2(200 BYTE),
  ATTRIBS_01        VARCHAR2(240 BYTE),
  ATTRIBS_02        VARCHAR2(240 BYTE),
  ATTRIBS_03        VARCHAR2(240 BYTE),
  ATTRIBS_04        VARCHAR2(240 BYTE),
  ATTRIBS_05        VARCHAR2(240 BYTE),
  ATTRIBS_06        VARCHAR2(240 BYTE),
  ATTRIBS_07        VARCHAR2(240 BYTE),
  ATTRIBS_08        VARCHAR2(240 BYTE),
  ATTRIBS_09        VARCHAR2(240 BYTE),
  ATTRIBS_10        VARCHAR2(240 BYTE),
  ATTRIBS_11        VARCHAR2(240 BYTE),
  ATTRIBS_12        VARCHAR2(240 BYTE),
  ATTRIBS_13        VARCHAR2(240 BYTE),
  ATTRIBS_14        VARCHAR2(240 BYTE),
  ATTRIBS_15        VARCHAR2(240 BYTE),
  ATTRIBD_01        DATE,
  ATTRIBD_02        DATE,
  ATTRIBD_03        DATE,
  ATTRIBD_04        DATE,
  ATTRIBD_05        DATE,
  ATTRIBD_06        DATE,
  ATTRIBD_07        DATE,
  ATTRIBD_08        DATE,
  ATTRIBD_09        DATE,
  ATTRIBD_10        DATE,
  ATTRIBD_11        DATE,
  ATTRIBD_12        DATE,
  ATTRIBD_13        DATE,
  ATTRIBD_14        DATE,
  ATTRIBD_15        DATE,
  ATTRIBN_01        NUMBER,
  ATTRIBN_02        NUMBER,
  ATTRIBN_03        NUMBER,
  ATTRIBN_04        NUMBER,
  ATTRIBN_05        NUMBER,
  ATTRIBN_06        NUMBER,
  ATTRIBN_07        NUMBER,
  ATTRIBN_08        NUMBER,
  ATTRIBN_09        NUMBER,
  ATTRIBN_10        NUMBER,
  ATTRIBN_11        NUMBER,
  ATTRIBN_12        NUMBER,
  ATTRIBN_13        NUMBER,
  ATTRIBN_14        NUMBER,
  ATTRIBN_15        NUMBER,
  CREATION_DATE     DATE                        DEFAULT sysdate               NOT NULL,
  CREATED_BY        VARCHAR2(30 BYTE)           DEFAULT user                  NOT NULL,
  LAST_UPDATE_DATE  DATE                        DEFAULT sysdate               NOT NULL,
  LAST_UPDATED_BY   VARCHAR2(30 BYTE)           DEFAULT user                  NOT NULL
);

CREATE INDEX DETAILS_FK_I ON DETAILS (parent_ID);


ALTER TABLE DETAILS ADD (
  CONSTRAINT DETAILS_FK 
 FOREIGN KEY (CONTEXT_ID) 
 REFERENCES DETAIL_CONTEXTS (ID));

GRANT SELECT ON DETAILS TO PLANNERREPORTS;
CREATE PUBLIC SYNONYM DETAILS FOR DETAILS;




