*** przedmioty w semestrze
SELECT DISTINCT SUB.ID, SUB.NAME
FROM CLASSES CLA, SUBJECTS SUB
WHERE CLA.SUB_ID = SUB.ID AND DAY BETWEEN TO_DATE('1997-12-12','YYYY-MM-DD') AND TO_DATE('2002-12-12','YYYY-MM-DD')
ORDER BY SUB.NAME

*** WYK£ADOWCY PRZEDMIOTU
SELECT DISTINCT LEC.FIRST_NAME || ' ' || LEC.LAST_NAME NAME 
FROM CLASSES CLA, LEC_CLA , LECTURERS LEC 
WHERE LEC_CLA.LEC_ID= LEC.ID AND LEC_CLA.CLA_ID= CLA.ID AND CLA.SUB_ID = 500040 AND DAY BETWEEN TO_DATE('1998/02/01','YYYY/MM/DD') AND TO_DATE('1998/06/02','YYYY/MM/DD') ORDER BY NAME